const mongoose = require('mongoose');
const dotenv = require('dotenv');
const bcrypt = require('bcryptjs');

dotenv.config();

const User = require('../models/User');
const Medicine = require('../models/Medicine');
const Batch = require('../models/Batch');
const Pharmacy = require('../models/Pharmacy');
const Inventory = require('../models/Inventory');
const Sale = require('../models/Sale');
const Report = require('../models/Report');
const AccessLog = require('../models/AccessLog');
const MedicineHistory = require('../models/MedicineHistory');

const seedDatabase = async () => {
  try {
    console.log('[Seed] Starting database cleanup and seeding...');

    // Clear existing data
    await Promise.all([
      User.deleteMany(),
      Medicine.deleteMany(),
      Batch.deleteMany(),
      Pharmacy.deleteMany(),
      Inventory.deleteMany(),
      Sale.deleteMany(),
      Report.deleteMany(),
      AccessLog.deleteMany(),
      MedicineHistory.deleteMany(),
    ]);

    console.log('[Seed] Cleared existing collections.');

    // 1. Create Users (User pre-save hook will hash passwords)
    const adminUser = await User.create({
      name: 'Dr. Tanvir Ahmed (Director)',
      email: 'admin@medcheckbd.com',
      phone: '+8801711000001',
      password: 'Admin@1234',
      role: 'admin',
    });

    const pharmacyOwner1 = await User.create({
      name: 'Mohammad Faruk Hossain',
      email: 'pharmacy@medcare.com',
      phone: '+8801819000002',
      password: 'Pharmacy@123',
      role: 'pharmacy',
    });

    const pharmacyOwner2 = await User.create({
      name: 'Kabir Chowdhury',
      email: 'lazz@lazzpharma.com',
      phone: '+8801712000003',
      password: 'Pharmacy@123',
      role: 'pharmacy',
    });

    const customerUser = await User.create({
      name: 'Shakil Mahmud',
      email: 'customer@gmail.com',
      phone: '+8801913000004',
      password: 'Customer@123',
      role: 'customer',
    });

    const customerUser2 = await User.create({
      name: 'Nusrat Jahan',
      email: 'nusrat@gmail.com',
      phone: '+8801614000005',
      password: 'Customer@123',
      role: 'customer',
    });

    console.log('[Seed] Created default users (Admin, Pharmacy, Customer).');

    // 2. Create Medicines (22 realistic Bangladeshi medicines)
    const medicinesData = [
      {
        name: 'Napa 500 mg',
        genericName: 'Paracetamol',
        manufacturer: 'Beximco Pharmaceuticals Ltd.',
        strength: '500 mg',
        dosageForm: 'Tablet',
        category: 'Analgesics & Antipyretics',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-012-0045',
        referencePrice: 1.20,
        barcode: '894110000101',
        description: 'First line treatment for mild to moderate fever and pain relief.',
        alerts: [],
      },
      {
        name: 'Napa Extra',
        genericName: 'Paracetamol + Caffeine',
        manufacturer: 'Beximco Pharmaceuticals Ltd.',
        strength: '500 mg + 65 mg',
        dosageForm: 'Tablet',
        category: 'Analgesics & Antipyretics',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-012-0046',
        referencePrice: 2.50,
        barcode: '894110000102',
        description: 'Enhanced fever and headache relief with caffeine synergism.',
        alerts: [],
      },
      {
        name: 'Napa One 1000 mg',
        genericName: 'Paracetamol',
        manufacturer: 'Beximco Pharmaceuticals Ltd.',
        strength: '1000 mg',
        dosageForm: 'Tablet',
        category: 'Analgesics & Antipyretics',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-012-0047',
        referencePrice: 2.50,
        barcode: '894110000103',
        description: 'High strength paracetamol tablet for persistent fever.',
        alerts: [],
      },
      {
        name: 'Ace Plus',
        genericName: 'Paracetamol + Caffeine',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '500 mg + 65 mg',
        dosageForm: 'Tablet',
        category: 'Analgesics & Antipyretics',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0189',
        referencePrice: 2.50,
        barcode: '894110000201',
        description: 'Effective headache, migraine, toothache, and bodily ache reliever.',
        alerts: [],
      },
      {
        name: 'Seclo 20 mg',
        genericName: 'Omeprazole',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '20 mg',
        dosageForm: 'Capsule',
        category: 'Proton Pump Inhibitors (PPI)',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0230',
        referencePrice: 6.00,
        barcode: '894110000202',
        description: 'Used for gastroesophageal reflux disease, gastric ulcers, and acidity.',
        alerts: [],
      },
      {
        name: 'Sergel 20 mg',
        genericName: 'Esomeprazole Magnesium',
        manufacturer: 'Incepta Pharmaceuticals Ltd.',
        strength: '20 mg',
        dosageForm: 'Capsule',
        category: 'Proton Pump Inhibitors (PPI)',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-024-0310',
        referencePrice: 7.00,
        barcode: '894110000301',
        description: 'Rapid control of acid secretion for peptic ulcer and GERD.',
        alerts: [],
      },
      {
        name: 'Maxpro 20 mg',
        genericName: 'Esomeprazole',
        manufacturer: 'Renata Limited',
        strength: '20 mg',
        dosageForm: 'Tablet',
        category: 'Proton Pump Inhibitors (PPI)',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-018-0112',
        referencePrice: 7.00,
        barcode: '894110000401',
        description: 'Enteric coated esomeprazole for prolonged acid suppression.',
        alerts: [],
      },
      {
        name: 'Pantonix 20 mg',
        genericName: 'Pantoprazole Sodium',
        manufacturer: 'Incepta Pharmaceuticals Ltd.',
        strength: '20 mg',
        dosageForm: 'Tablet',
        category: 'Proton Pump Inhibitors (PPI)',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-024-0322',
        referencePrice: 7.00,
        barcode: '894110000302',
        description: 'Indicated for erosive esophagitis and duodenal ulcers.',
        alerts: [],
      },
      {
        name: 'Fexo 120 mg',
        genericName: 'Fexofenadine Hydrochloride',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '120 mg',
        dosageForm: 'Tablet',
        category: 'Antihistamines',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0415',
        referencePrice: 9.00,
        barcode: '894110000203',
        description: 'Non-sedating antihistamine for allergic rhinitis and skin allergies.',
        alerts: [],
      },
      {
        name: 'Alatrol 10 mg',
        genericName: 'Cetirizine Dihydrochloride',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '10 mg',
        dosageForm: 'Tablet',
        category: 'Antihistamines',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0428',
        referencePrice: 3.50,
        barcode: '894110000204',
        description: 'Rapid acting allergy and urticaria treatment.',
        alerts: [],
      },
      {
        name: 'Monas 10 mg',
        genericName: 'Montelukast Sodium',
        manufacturer: 'Acme Laboratories Ltd.',
        strength: '10 mg',
        dosageForm: 'Tablet',
        category: 'Respiratory / Anti-asthmatic',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-031-0511',
        referencePrice: 16.00,
        barcode: '894110000501',
        description: 'Leukotriene receptor antagonist for chronic asthma and allergic rhinitis.',
        alerts: [],
      },
      {
        name: 'Ceevit 250 mg',
        genericName: 'Ascorbic Acid (Vitamin C)',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '250 mg',
        dosageForm: 'Tablet',
        category: 'Vitamins & Minerals',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0550',
        referencePrice: 1.80,
        barcode: '894110000205',
        description: 'Chewable vitamin C supplement for immunity and wound healing.',
        alerts: [],
      },
      {
        name: 'Filwel Gold',
        genericName: 'Multivitamin & Multimineral (A to Z)',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: 'Comprehensive 32 nutrients',
        dosageForm: 'Tablet',
        category: 'Vitamins & Minerals',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0610',
        referencePrice: 5.50,
        barcode: '894110000206',
        description: 'Daily adult nutritional health booster tablet.',
        alerts: [],
      },
      {
        name: 'Coralcal-D',
        genericName: 'Calcium Carbonate (Coral source) + Vitamin D3',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '500 mg + 200 IU',
        dosageForm: 'Tablet',
        category: 'Vitamins & Minerals',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0630',
        referencePrice: 8.00,
        barcode: '894110000207',
        description: 'Bone density and osteoporosis prevention.',
        alerts: [],
      },
      {
        name: 'Bizoran 5/20 mg',
        genericName: 'Amlodipine + Olmesartan Medoxomil',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '5 mg + 20 mg',
        dosageForm: 'Tablet',
        category: 'Cardiovascular / Anti-hypertensive',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0710',
        referencePrice: 15.00,
        barcode: '894110000208',
        description: 'Dual combination antihypertensive medication.',
        alerts: [],
      },
      {
        name: 'Torax 10 mg',
        genericName: 'Ketorolac Tromethamine',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '10 mg',
        dosageForm: 'Tablet',
        category: 'Analgesics / NSAID',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0780',
        referencePrice: 10.00,
        barcode: '894110000209',
        description: 'Short term management of moderate to severe acute pain.',
        alerts: [],
      },
      {
        name: 'Azithrocin 500 mg',
        genericName: 'Azithromycin',
        manufacturer: 'Beximco Pharmaceuticals Ltd.',
        strength: '500 mg',
        dosageForm: 'Tablet',
        category: 'Antibiotics',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-012-0850',
        referencePrice: 35.00,
        barcode: '894110000104',
        description: 'Macrolide antibiotic for upper and lower respiratory infections.',
        alerts: [],
      },
      {
        name: 'Moxaclav 625 mg',
        genericName: 'Amoxicillin + Clavulanic Acid',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '500 mg + 125 mg',
        dosageForm: 'Tablet',
        category: 'Antibiotics',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0912',
        referencePrice: 38.00,
        barcode: '894110000210',
        description: 'Broad spectrum penicillin antibiotic with beta-lactamase inhibitor.',
        alerts: [],
      },
      {
        name: 'Esonix 20 mg',
        genericName: 'Esomeprazole',
        manufacturer: 'Incepta Pharmaceuticals Ltd.',
        strength: '20 mg',
        dosageForm: 'Tablet',
        category: 'Proton Pump Inhibitors (PPI)',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-024-0980',
        referencePrice: 7.00,
        barcode: '894110000303',
        description: 'Proton pump inhibitor for healing erosive esophagitis.',
        alerts: [],
      },
      {
        name: 'D-Rise 20000 IU',
        genericName: 'Cholecalciferol (Vitamin D3)',
        manufacturer: 'Renata Limited',
        strength: '20000 IU',
        dosageForm: 'Capsule',
        category: 'Vitamins & Minerals',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-018-1020',
        referencePrice: 40.00,
        barcode: '894110000402',
        description: 'High dose weekly vitamin D3 therapeutic capsule.',
        alerts: [],
      },
      {
        name: 'Calbo-D',
        genericName: 'Calcium Carbonate + Vitamin D3',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '500 mg + 200 IU',
        dosageForm: 'Tablet',
        category: 'Vitamins & Minerals',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-1110',
        referencePrice: 7.00,
        barcode: '894110000211',
        description: 'Calcium supplement with vitamin D for bone integrity.',
        alerts: [],
      },
      {
        name: 'Reflu-X 10 mg',
        genericName: 'Domperidone',
        manufacturer: 'Opsonin Pharma Limited',
        strength: '10 mg',
        dosageForm: 'Tablet',
        category: 'Gastroprokinetic',
        registrationStatus: 'NEEDS REVIEW',
        registrationNumber: 'DAR-042-1240',
        referencePrice: 3.00,
        barcode: '894110000601',
        description: 'Motility stimulant and anti-emetic.',
        alerts: [
          {
            alertType: 'QUALITY_WARNING',
            message: 'Packaging batch printing under manufacturer review by regulatory authorities.',
            date: new Date(),
          },
        ],
      },
      {
        name: 'Panadol 500 mg',
        genericName: 'Paracetamol',
        manufacturer: 'GlaxoSmithKline Bangladesh Ltd.',
        strength: '500 mg',
        dosageForm: 'Tablet',
        category: 'Analgesics & Antipyretics',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-030-0012',
        referencePrice: 1.50,
        barcode: '894110000701',
        description: 'Fast acting fever and headache pain relief.',
        alerts: [],
      },
      {
        name: 'Fast 500 mg',
        genericName: 'Paracetamol',
        manufacturer: 'Acme Laboratories Ltd.',
        strength: '500 mg',
        dosageForm: 'Tablet',
        category: 'Analgesics & Antipyretics',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-031-0088',
        referencePrice: 1.20,
        barcode: '894110000502',
        description: 'General antipyretic for mild pain and fever relief.',
        alerts: [],
      },
      {
        name: 'Renova 500 mg',
        genericName: 'Paracetamol',
        manufacturer: 'Opsonin Pharma Limited',
        strength: '500 mg',
        dosageForm: 'Tablet',
        category: 'Analgesics & Antipyretics',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-042-0120',
        referencePrice: 1.20,
        barcode: '894110000602',
        description: 'Paracetamol tablet formulation by Opsonin.',
        alerts: [],
      },
      {
        name: 'Ace 500 mg',
        genericName: 'Paracetamol',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '500 mg',
        dosageForm: 'Tablet',
        category: 'Analgesics & Antipyretics',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0188',
        referencePrice: 1.20,
        barcode: '894110000212',
        description: 'Core paracetamol brand of Square Pharmaceuticals.',
        alerts: [],
      },
      {
        name: 'Napa Syrup 120 mg/5ml',
        genericName: 'Paracetamol',
        manufacturer: 'Beximco Pharmaceuticals Ltd.',
        strength: '120 mg / 5 ml (60 ml bottle)',
        dosageForm: 'Syrup',
        category: 'Analgesics & Antipyretics',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-012-0048',
        referencePrice: 35.00,
        barcode: '894110000105',
        description: 'Pediatric fever suspension syrup.',
        alerts: [],
      },
      {
        name: 'Losectil 20 mg',
        genericName: 'Omeprazole',
        manufacturer: 'Eskayef Pharmaceuticals Ltd.',
        strength: '20 mg',
        dosageForm: 'Capsule',
        category: 'Proton Pump Inhibitors (PPI)',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-022-0190',
        referencePrice: 6.00,
        barcode: '894110000801',
        description: 'Standard gastric ulcer and acidity management capsule.',
        alerts: [],
      },
      {
        name: 'Finix 20 mg',
        genericName: 'Rabeprazole Sodium',
        manufacturer: 'Opsonin Pharma Limited',
        strength: '20 mg',
        dosageForm: 'Tablet',
        category: 'Proton Pump Inhibitors (PPI)',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-042-0210',
        referencePrice: 7.00,
        barcode: '894110000603',
        description: 'Fast acting rabeprazole proton pump inhibitor.',
        alerts: [],
      },
      {
        name: 'Entacyd Plus',
        genericName: 'Aluminium Hydroxide + Magnesium Hydroxide + Simethicone',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: 'Standard Chewable',
        dosageForm: 'Tablet',
        category: 'Antacids & Antiflatulents',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0290',
        referencePrice: 2.50,
        barcode: '894110000213',
        description: 'Chewable antacid for immediate heartburn and gas relief.',
        alerts: [],
      },
      {
        name: 'Flagyl 400 mg',
        genericName: 'Metronidazole',
        manufacturer: 'Sanofi Bangladesh Ltd.',
        strength: '400 mg',
        dosageForm: 'Tablet',
        category: 'Antiprotozoal & Antibacterial',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-015-0340',
        referencePrice: 2.20,
        barcode: '894110000901',
        description: 'Treatment for amoebiasis, giardiasis, and anaerobic infections.',
        alerts: [],
      },
      {
        name: 'Amodis 400 mg',
        genericName: 'Metronidazole',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '400 mg',
        dosageForm: 'Tablet',
        category: 'Antiprotozoal & Antibacterial',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0345',
        referencePrice: 2.00,
        barcode: '894110000214',
        description: 'Metronidazole formulation by Square.',
        alerts: [],
      },
      {
        name: 'Ciprocin 500 mg',
        genericName: 'Ciprofloxacin',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '500 mg',
        dosageForm: 'Tablet',
        category: 'Antibiotics / Fluoroquinolones',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0480',
        referencePrice: 15.00,
        barcode: '894110000215',
        description: 'Broad spectrum antibiotic for urinary tract, typhoid and enteric infections.',
        alerts: [],
      },
      {
        name: 'Ciprox 500 mg',
        genericName: 'Ciprofloxacin',
        manufacturer: 'Beximco Pharmaceuticals Ltd.',
        strength: '500 mg',
        dosageForm: 'Tablet',
        category: 'Antibiotics / Fluoroquinolones',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-012-0482',
        referencePrice: 15.00,
        barcode: '894110000106',
        description: 'Ciprofloxacin tablet formulation by Beximco.',
        alerts: [],
      },
      {
        name: 'Zimax 500 mg',
        genericName: 'Azithromycin',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '500 mg',
        dosageForm: 'Tablet',
        category: 'Antibiotics',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0520',
        referencePrice: 35.00,
        barcode: '894110000216',
        description: 'Macrolide antibiotic for upper and lower respiratory infections.',
        alerts: [],
      },
      {
        name: 'Fimoxyl 500 mg',
        genericName: 'Amoxicillin',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '500 mg',
        dosageForm: 'Capsule',
        category: 'Antibiotics',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0560',
        referencePrice: 7.50,
        barcode: '894110000217',
        description: 'Broad spectrum penicillin antibiotic.',
        alerts: [],
      },
      {
        name: 'Cef-3 200 mg',
        genericName: 'Cefixime',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '200 mg',
        dosageForm: 'Capsule',
        category: 'Antibiotics / Cephalosporins',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0590',
        referencePrice: 45.00,
        barcode: '894110000218',
        description: 'Third generation cephalosporin antibiotic.',
        alerts: [],
      },
      {
        name: 'Histacin 4 mg',
        genericName: 'Chlorpheniramine Maleate',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '4 mg',
        dosageForm: 'Tablet',
        category: 'Antihistamines',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0620',
        referencePrice: 0.50,
        barcode: '894110000219',
        description: 'Standard allergy, runny nose, and sneezing relief.',
        alerts: [],
      },
      {
        name: 'Telfast 120 mg',
        genericName: 'Fexofenadine Hydrochloride',
        manufacturer: 'Sanofi Bangladesh Ltd.',
        strength: '120 mg',
        dosageForm: 'Tablet',
        category: 'Antihistamines',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-015-0670',
        referencePrice: 10.00,
        barcode: '894110000902',
        description: 'Original non-drowsy fexofenadine formulation.',
        alerts: [],
      },
      {
        name: 'Rupafin 10 mg',
        genericName: 'Rupatadine',
        manufacturer: 'Beximco Pharmaceuticals Ltd.',
        strength: '10 mg',
        dosageForm: 'Tablet',
        category: 'Antihistamines',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-012-0690',
        referencePrice: 12.00,
        barcode: '894110000107',
        description: 'Second-generation antihistamine and PAF antagonist.',
        alerts: [],
      },
      {
        name: 'Bilash 20 mg',
        genericName: 'Bilastine',
        manufacturer: 'Incepta Pharmaceuticals Ltd.',
        strength: '20 mg',
        dosageForm: 'Tablet',
        category: 'Antihistamines',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-024-0710',
        referencePrice: 15.00,
        barcode: '894110000304',
        description: 'Non-sedating antihistamine for allergic rhino-conjunctivitis.',
        alerts: [],
      },
      {
        name: 'Montene 10 mg',
        genericName: 'Montelukast Sodium',
        manufacturer: 'Incepta Pharmaceuticals Ltd.',
        strength: '10 mg',
        dosageForm: 'Tablet',
        category: 'Respiratory / Anti-asthmatic',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-024-0740',
        referencePrice: 16.00,
        barcode: '894110000305',
        description: 'Montelukast asthma and rhinitis tablet.',
        alerts: [],
      },
      {
        name: 'Provair 10 mg',
        genericName: 'Montelukast Sodium',
        manufacturer: 'Unimed Unihealth Pharmaceuticals',
        strength: '10 mg',
        dosageForm: 'Tablet',
        category: 'Respiratory / Anti-asthmatic',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-035-0760',
        referencePrice: 16.00,
        barcode: '894110001001',
        description: 'Asthma prophylactic and allergic rhinitis treatment.',
        alerts: [],
      },
      {
        name: 'Odmon 10 mg',
        genericName: 'Montelukast Sodium',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '10 mg',
        dosageForm: 'Tablet',
        category: 'Respiratory / Anti-asthmatic',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0770',
        referencePrice: 16.00,
        barcode: '894110000220',
        description: 'Montelukast formulation by Square.',
        alerts: [],
      },
      {
        name: 'Adovas Syrup',
        genericName: 'Adhatoda Vasica + Ocimum Sanctum (Tulsi)',
        manufacturer: 'Square Herbal & Ayurvedic Ltd.',
        strength: '100 ml bottle',
        dosageForm: 'Syrup',
        category: 'Herbal Cough Remedies',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0810',
        referencePrice: 85.00,
        barcode: '894110000221',
        description: 'Soothing natural syrup for dry and productive cough.',
        alerts: [],
      },
      {
        name: 'Tusca Syrup',
        genericName: 'Dextromethorphan + Phenylephrine',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '100 ml bottle',
        dosageForm: 'Syrup',
        category: 'Cough & Cold Expectorants',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0820',
        referencePrice: 80.00,
        barcode: '894110000222',
        description: 'Relief of cough and nasal congestion.',
        alerts: [],
      },
      {
        name: 'Basok Syrup',
        genericName: 'Adhatoda Vasica Extract',
        manufacturer: 'Hamdard Laboratories (Waqf) Bangladesh',
        strength: '100 ml bottle',
        dosageForm: 'Syrup',
        category: 'Herbal Cough Remedies',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-050-0830',
        referencePrice: 75.00,
        barcode: '894110001101',
        description: 'Traditional Vasaka syrup for cough and chest congestion.',
        alerts: [],
      },
      {
        name: 'Dextrim Syrup',
        genericName: 'Dextromethorphan Hydrobromide',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '100 ml bottle',
        dosageForm: 'Syrup',
        category: 'Cough Suppressants',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0840',
        referencePrice: 65.00,
        barcode: '894110000223',
        description: 'Dry irritating cough relief syrup.',
        alerts: [],
      },
      {
        name: 'Windel 2 mg',
        genericName: 'Salbutamol',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '2 mg',
        dosageForm: 'Tablet',
        category: 'Bronchodilators',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0870',
        referencePrice: 0.35,
        barcode: '894110000224',
        description: 'Relief of bronchospasm in bronchial asthma.',
        alerts: [],
      },
      {
        name: 'Rolac 10 mg',
        genericName: 'Ketorolac Tromethamine',
        manufacturer: 'Incepta Pharmaceuticals Ltd.',
        strength: '10 mg',
        dosageForm: 'Tablet',
        category: 'Analgesics / NSAID',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-024-0890',
        referencePrice: 10.00,
        barcode: '894110000306',
        description: 'Nonsteroidal anti-inflammatory for acute moderate pain.',
        alerts: [],
      },
      {
        name: 'Xenole 500 mg',
        genericName: 'Naproxen + Esomeprazole',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '500 mg + 20 mg',
        dosageForm: 'Tablet',
        category: 'Analgesics / NSAID',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0930',
        referencePrice: 12.00,
        barcode: '894110000225',
        description: 'Arthritis and joint pain relief with gastric protective coating.',
        alerts: [],
      },
      {
        name: 'Voveran 50 mg',
        genericName: 'Diclofenac Sodium',
        manufacturer: 'Novartis (Bangladesh) Ltd.',
        strength: '50 mg',
        dosageForm: 'Tablet',
        category: 'Analgesics / NSAID',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-008-0950',
        referencePrice: 4.50,
        barcode: '894110001201',
        description: 'Anti-inflammatory for musculoskeletal disorders and acute gout.',
        alerts: [],
      },
      {
        name: 'Flexi 100 mg',
        genericName: 'Aceclofenac',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '100 mg',
        dosageForm: 'Tablet',
        category: 'Analgesics / NSAID',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-0970',
        referencePrice: 5.00,
        barcode: '894110000226',
        description: 'Osteoarthritis, rheumatoid arthritis and back pain relief.',
        alerts: [],
      },
      {
        name: 'Civit 250 mg',
        genericName: 'Ascorbic Acid (Vitamin C)',
        manufacturer: 'Incepta Pharmaceuticals Ltd.',
        strength: '250 mg',
        dosageForm: 'Tablet',
        category: 'Vitamins & Minerals',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-024-1010',
        referencePrice: 1.80,
        barcode: '894110000307',
        description: 'Chewable orange vitamin C tablet.',
        alerts: [],
      },
      {
        name: 'Bextram Gold',
        genericName: 'Comprehensive 32 Multivitamin & Multimineral',
        manufacturer: 'Beximco Pharmaceuticals Ltd.',
        strength: 'Complete Formula',
        dosageForm: 'Tablet',
        category: 'Vitamins & Minerals',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-012-1040',
        referencePrice: 6.00,
        barcode: '894110000108',
        description: 'Premium daily multivitamin supplement.',
        alerts: [],
      },
      {
        name: 'Neuro-B',
        genericName: 'Vitamin B1 + Vitamin B6 + Vitamin B12',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '100 mg + 200 mg + 200 mcg',
        dosageForm: 'Tablet',
        category: 'Vitamins & Neurological Health',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-1080',
        referencePrice: 7.50,
        barcode: '894110000227',
        description: 'Peripheral neuropathy, neuralgia and vitamin B deficiency.',
        alerts: [],
      },
      {
        name: 'Aristovit B',
        genericName: 'Vitamin B-Complex',
        manufacturer: 'AristoPharma Ltd.',
        strength: 'B1, B2, B6, Nicotinamide',
        dosageForm: 'Tablet',
        category: 'Vitamins & Minerals',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-028-1090',
        referencePrice: 3.00,
        barcode: '894110001301',
        description: 'Essential Vitamin B complex tonic.',
        alerts: [],
      },
      {
        name: 'Osartil 50 mg',
        genericName: 'Losartan Potassium',
        manufacturer: 'Incepta Pharmaceuticals Ltd.',
        strength: '50 mg',
        dosageForm: 'Tablet',
        category: 'Cardiovascular / Anti-hypertensive',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-024-1140',
        referencePrice: 8.00,
        barcode: '894110000308',
        description: 'First line blood pressure control medication.',
        alerts: [],
      },
      {
        name: 'Angilock 50 mg',
        genericName: 'Losartan Potassium',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '50 mg',
        dosageForm: 'Tablet',
        category: 'Cardiovascular / Anti-hypertensive',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-1150',
        referencePrice: 8.00,
        barcode: '894110000228',
        description: 'Antihypertensive ARB tablet by Square.',
        alerts: [],
      },
      {
        name: 'Betacap 20 mg',
        genericName: 'Propranolol Hydrochloride',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '20 mg',
        dosageForm: 'Tablet',
        category: 'Cardiovascular / Beta-blockers',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-1170',
        referencePrice: 1.50,
        barcode: '894110000229',
        description: 'Management of hypertension, angina, and anxiety tremors.',
        alerts: [],
      },
      {
        name: 'Comet 500 mg',
        genericName: 'Metformin Hydrochloride',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '500 mg',
        dosageForm: 'Tablet',
        category: 'Antidiabetic Agents',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-1210',
        referencePrice: 4.00,
        barcode: '894110000230',
        description: 'First-line type 2 diabetes glycemic control.',
        alerts: [],
      },
      {
        name: 'Savlon Antiseptic Liquid',
        genericName: 'Chlorhexidine Gluconate + Cetrimide',
        manufacturer: 'ACI Limited',
        strength: '100 ml bottle',
        dosageForm: 'Syrup',
        category: 'Antiseptics & Disinfectants',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-004-1260',
        referencePrice: 50.00,
        barcode: '894110001401',
        description: 'First aid wound cleansing and household antiseptic.',
        alerts: [],
      },
      {
        name: 'Viodin 10% Solution',
        genericName: 'Povidone Iodine',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '100 ml bottle',
        dosageForm: 'Syrup',
        category: 'Antiseptics & Disinfectants',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-1280',
        referencePrice: 70.00,
        barcode: '894110000231',
        description: 'Topical microbicide for cuts, wounds, and pre-op disinfection.',
        alerts: [],
      },
      {
        name: 'Burnsil Cream',
        genericName: 'Silver Sulfadiazine',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '25 gm tube',
        dosageForm: 'Ointment',
        category: 'Topical Antibacterial / Burns',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-1310',
        referencePrice: 60.00,
        barcode: '894110000232',
        description: 'Burn wound prevention of infection and healing.',
        alerts: [],
      },
      {
        name: 'Pevisone Cream',
        genericName: 'Econazole Nitrate + Triamcinolone Acetonide',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '10 gm tube',
        dosageForm: 'Ointment',
        category: 'Antifungal & Anti-inflammatory',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-1330',
        referencePrice: 75.00,
        barcode: '894110000233',
        description: 'Inflammatory fungal skin infections treatment.',
        alerts: [],
      },
      {
        name: 'Betameson-N',
        genericName: 'Betamethasone + Neomycin',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '15 gm tube',
        dosageForm: 'Ointment',
        category: 'Dermatological Corticosteroids',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-1350',
        referencePrice: 40.00,
        barcode: '894110000234',
        description: 'Steroid-antibiotic ointment for infected eczema and dermatitis.',
        alerts: [],
      },
      {
        name: 'Clobit Ointment',
        genericName: 'Clobetasol Propionate',
        manufacturer: 'Square Pharmaceuticals PLC',
        strength: '10 gm tube',
        dosageForm: 'Ointment',
        category: 'Dermatological Corticosteroids',
        registrationStatus: 'REGISTERED',
        registrationNumber: 'DAR-001-1380',
        referencePrice: 55.00,
        barcode: '894110000235',
        description: 'Super-potent topical corticosteroid for resistant psoriasis.',
        alerts: [],
      },
    ];

    const createdMedicines = await Medicine.create(medicinesData);
    console.log(`[Seed] Created ${createdMedicines.length} verified medicines.`);

    // 3. Create Batches for each medicine
    const batchesData = [];
    const now = new Date();

    createdMedicines.forEach((med, idx) => {
      const firstWord = med.name.split(' ')[0].toUpperCase().replace(/[^A-Z]/g, '');
      const code = firstWord || 'MED';
      // Standard active batch
      batchesData.push({
        medicineId: med._id,
        batchNumber: `${code}-2026-01`,
        manufacturingDate: new Date('2025-06-01'),
        expiryDate: new Date('2027-12-31'),
        status: 'VALID',
        notes: 'Standard batch released for commercial distribution.',
      });

      // Secondary batch
      batchesData.push({
        medicineId: med._id,
        batchNumber: `${code}-2026-02`,
        manufacturingDate: new Date('2025-10-15'),
        expiryDate: new Date('2028-05-30'),
        status: 'VALID',
        notes: 'High compliance secondary run.',
      });

      // Introduce specific test batches for demonstration
      if (idx === 0) {
        // Napa has an Expiring Soon batch for demo
        batchesData.push({
          medicineId: med._id,
          batchNumber: 'NAPA-EXP-26',
          manufacturingDate: new Date('2024-01-01'),
          expiryDate: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 25), // 25 days from now
          status: 'EXPIRING_SOON',
          notes: 'Batch approaching 30-day expiry threshold.',
        });
        // Napa has an Expired batch for demo
        batchesData.push({
          medicineId: med._id,
          batchNumber: 'NAPA-OLD-99',
          manufacturingDate: new Date('2023-01-01'),
          expiryDate: new Date('2025-01-01'),
          status: 'EXPIRED',
          notes: 'Expired test batch. Do not dispense.',
        });
      }

      if (idx === 3) {
        // Ace Plus has a reported/suspicious batch
        batchesData.push({
          medicineId: med._id,
          batchNumber: 'ACE-FLAG-88',
          manufacturingDate: new Date('2025-02-01'),
          expiryDate: new Date('2027-02-01'),
          status: 'SUSPICIOUS',
          reportedCounterfeitCount: 3,
          notes: 'Reported for inconsistent blister foil thickness in local area.',
        });
      }
    });

    const createdBatches = await Batch.create(batchesData);
    console.log(`[Seed] Created ${createdBatches.length} medicine batches.`);

    // 4. Create Bangladeshi Pharmacies (including chain branches across Dhanmondi, Mirpur, Uttara, etc.)
    const pharmaciesData = [
      {
        name: 'MedCare Pharmacy Dhanmondi',
        ownerName: 'Mohammad Faruk Hossain',
        phone: '+8801819000002',
        email: 'pharmacy@medcare.com',
        address: 'House 42, Road 7/A, Dhanmondi',
        area: 'Dhanmondi',
        division: 'Dhaka',
        licenseNumber: 'DL-DHK-2023-4412',
        verified: true,
        status: 'Approved',
        openingHours: '24 Hours',
        isOpenNow: true,
        userId: pharmacyOwner1._id,
      },
      {
        name: 'MedCare Pharmacy Mirpur',
        ownerName: 'Mohammad Faruk Hossain',
        phone: '+8801819000021',
        email: 'mirpur@medcare.com',
        address: 'Plot 14, Main Road, Section 10, Mirpur',
        area: 'Mirpur',
        division: 'Dhaka',
        licenseNumber: 'DL-DHK-2023-4418',
        verified: true,
        status: 'Approved',
        openingHours: '24 Hours',
        isOpenNow: true,
        userId: pharmacyOwner1._id,
      },
      {
        name: 'MedCare Pharmacy Uttara',
        ownerName: 'Mohammad Faruk Hossain',
        phone: '+8801819000022',
        email: 'uttara@medcare.com',
        address: 'Sector 3, Jashimuddin Avenue, Uttara',
        area: 'Uttara',
        division: 'Dhaka',
        licenseNumber: 'DL-DHK-2023-4419',
        verified: true,
        status: 'Approved',
        openingHours: '8:00 AM - 11:30 PM',
        isOpenNow: true,
        userId: pharmacyOwner1._id,
      },
      {
        name: 'Lazz Pharma Dhanmondi',
        ownerName: 'Kabir Chowdhury',
        phone: '+8801712000003',
        email: 'lazz@lazzpharma.com',
        address: 'Plot 12, Mirpur Road, Dhanmondi 27',
        area: 'Dhanmondi',
        division: 'Dhaka',
        licenseNumber: 'DL-DHK-2022-1002',
        verified: true,
        status: 'Approved',
        openingHours: '24 Hours',
        isOpenNow: true,
        userId: pharmacyOwner2._id,
      },
      {
        name: 'Lazz Pharma Mirpur',
        ownerName: 'Kabir Chowdhury',
        phone: '+8801712000023',
        email: 'mirpur@lazzpharma.com',
        address: 'Mirpur 10 Circle, Begum Rokeya Sarani, Mirpur',
        area: 'Mirpur',
        division: 'Dhaka',
        licenseNumber: 'DL-DHK-2022-1008',
        verified: true,
        status: 'Approved',
        openingHours: '24 Hours',
        isOpenNow: true,
        userId: pharmacyOwner2._id,
      },
      {
        name: 'Lazz Pharma Uttara',
        ownerName: 'Kabir Chowdhury',
        phone: '+8801712000024',
        email: 'uttara@lazzpharma.com',
        address: 'House 18, Road 7, Sector 4, Uttara',
        area: 'Uttara',
        division: 'Dhaka',
        licenseNumber: 'DL-DHK-2022-1009',
        verified: true,
        status: 'Approved',
        openingHours: '24 Hours',
        isOpenNow: true,
        userId: pharmacyOwner2._id,
      },
      {
        name: 'Tamanna Pharmacy Mirpur',
        ownerName: 'Anisur Rahman',
        phone: '+8801715000006',
        email: 'tamanna@mirpurpharma.com',
        address: 'Section 10, Mirpur Roundabout, Mirpur',
        area: 'Mirpur',
        division: 'Dhaka',
        licenseNumber: 'DL-DHK-2023-8821',
        verified: true,
        status: 'Approved',
        openingHours: '8:00 AM - 12:00 AM',
        isOpenNow: true,
        userId: pharmacyOwner1._id,
      },
      {
        name: 'Popular Medicine Corner Uttara',
        ownerName: 'Mustafa Kamal',
        phone: '+8801918000007',
        email: 'popular@uttarapharma.com',
        address: 'Sector 3, Jashimuddin Avenue, Uttara',
        area: 'Uttara',
        division: 'Dhaka',
        licenseNumber: 'DL-DHK-2024-3319',
        verified: true,
        status: 'Approved',
        openingHours: '8:00 AM - 11:30 PM',
        isOpenNow: true,
        userId: pharmacyOwner1._id,
      },
      {
        name: 'Care & Cure Pharmacy Mohammadpur',
        ownerName: 'Rezaul Karim',
        phone: '+8801817000008',
        email: 'carecure@mohammadpur.com',
        address: 'Asad Gate Main Road, Mohammadpur',
        area: 'Mohammadpur',
        division: 'Dhaka',
        licenseNumber: 'DL-DHK-2023-5591',
        verified: true,
        status: 'Approved',
        openingHours: '9:00 AM - 11:00 PM',
        isOpenNow: true,
        userId: pharmacyOwner1._id,
      },
      {
        name: 'Gulshan Health Mart',
        ownerName: 'Sarah Zaman',
        phone: '+8801716000009',
        email: 'gulshan@healthmart.com',
        address: 'Gulshan 2 Circle, Road 113',
        area: 'Gulshan',
        division: 'Dhaka',
        licenseNumber: 'DL-DHK-2024-9988',
        verified: true,
        status: 'Approved',
        openingHours: '24 Hours',
        isOpenNow: true,
        userId: pharmacyOwner1._id,
      },
      {
        name: 'Green Life Drug House Banani',
        ownerName: 'Shafiqul Islam',
        phone: '+8801618000010',
        email: 'greenlife@bananipharm.com',
        address: 'Block B, Kamal Ataturk Avenue, Banani',
        area: 'Banani',
        division: 'Dhaka',
        licenseNumber: 'DL-DHK-2023-7744',
        verified: true,
        status: 'Approved',
        openingHours: '8:30 AM - 11:00 PM',
        isOpenNow: true,
        userId: pharmacyOwner1._id,
      },
      {
        name: 'Chittagong Medical Store',
        ownerName: 'Moinuddin Ahmed',
        phone: '+8801812000011',
        email: 'ctgmed@chittagongpharma.com',
        address: 'GEC Circle, CDA Avenue',
        area: 'Chittagong',
        division: 'Chittagong',
        licenseNumber: 'DL-CTG-2023-2201',
        verified: true,
        status: 'Approved',
        openingHours: '8:00 AM - 11:00 PM',
        isOpenNow: true,
        userId: pharmacyOwner1._id,
      },
      {
        name: 'Sylhet Central Dispensary',
        ownerName: 'Jashim Uddin',
        phone: '+8801719000012',
        email: 'sylhet@centraldispensary.com',
        address: 'Zindabazar Point, Sylhet Sadar',
        area: 'Sylhet',
        division: 'Sylhet',
        licenseNumber: 'DL-SYL-2023-1144',
        verified: true,
        status: 'Approved',
        openingHours: '9:00 AM - 10:30 PM',
        isOpenNow: true,
        userId: pharmacyOwner1._id,
      },
      {
        name: 'Rajshahi Wellness Pharmacy',
        ownerName: 'Ziaul Hoque',
        phone: '+8801511000013',
        email: 'rajshahi@wellness.com',
        address: 'Shaheb Bazar, Rajshahi',
        area: 'Rajshahi',
        division: 'Rajshahi',
        licenseNumber: 'DL-RAJ-2024-0091',
        verified: false,
        status: 'Pending',
        openingHours: '8:00 AM - 10:00 PM',
        isOpenNow: true,
        userId: pharmacyOwner1._id,
      },
    ];

    const createdPharmacies = await Pharmacy.create(pharmaciesData);
    console.log(`[Seed] Created ${createdPharmacies.length} pharmacies across Bangladesh.`);

    // 5. Populate Inventories for All Pharmacies
    const inventoryData = [];
    const mainPharmacy = createdPharmacies[0]; // MedCare Pharmacy Dhanmondi

    createdPharmacies.forEach((pharmacy, pIdx) => {
      // Determine how many medicines this pharmacy stocks
      const medCount = pharmacy.verified ? Math.min(createdMedicines.length, 50 + (pIdx % 15)) : 25;

      createdMedicines.slice(0, medCount).forEach((med, mIdx) => {
        const medBatches = createdBatches.filter((b) => String(b.medicineId) === String(med._id));
        const activeBatch = medBatches[0] || null;

        if (activeBatch) {
          // Dynamic pricing: benchmark +/- small realistic variance
          let sellingPrice = med.referencePrice;
          const variance = ((pIdx + mIdx) % 5) - 2;
          if (variance === 2) sellingPrice = Number((med.referencePrice + 0.30).toFixed(2));
          else if (variance === 1) sellingPrice = Number((med.referencePrice + 0.15).toFixed(2));
          else if (variance === -1) sellingPrice = Number(Math.max(0.5, med.referencePrice - 0.10).toFixed(2));
          else if (variance === -2) sellingPrice = Number(Math.max(0.5, med.referencePrice - 0.20).toFixed(2));
          else sellingPrice = Number(med.referencePrice.toFixed(2));

          let quantity = 30 + ((pIdx * 7 + mIdx * 3) % 40);
          if (mIdx === 2 && pIdx === 0) quantity = 4; // LOW STOCK
          if (mIdx === 5 && pIdx === 1) quantity = 0; // OUT OF STOCK

          inventoryData.push({
            pharmacyId: pharmacy._id,
            medicineId: med._id,
            batchId: activeBatch._id,
            quantity,
            purchasePrice: Number((med.referencePrice * 0.85).toFixed(2)),
            sellingPrice,
          });
        }
      });
    });

    const createdInventory = await Inventory.create(inventoryData);
    console.log(`[Seed] Created ${createdInventory.length} inventory records with dynamic price variances.`);

    // 6. Create Sample Sales and Receipts
    const sampleSale = await Sale.create({
      receiptId: 'MC-2026-784102',
      pharmacyId: mainPharmacy._id,
      customerId: customerUser._id,
      customerName: customerUser.name,
      customerPhone: customerUser.phone,
      items: [
        {
          medicineId: createdMedicines[0]._id,
          medicineName: createdMedicines[0].name,
          genericName: createdMedicines[0].genericName,
          batchNumber: 'NAPA-2026-01',
          quantity: 20,
          unitPrice: 1.20,
          totalPrice: 24.00,
        },
        {
          medicineId: createdMedicines[4]._id,
          medicineName: createdMedicines[4].name,
          genericName: createdMedicines[4].genericName,
          batchNumber: 'SEC-2026-01',
          quantity: 14,
          unitPrice: 6.00,
          totalPrice: 84.00,
        },
      ],
      subtotal: 108.00,
      discount: 8.00,
      totalPrice: 100.00,
      paymentMethod: 'bKash',
      date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2), // 2 days ago
    });

    const mirpurPharmacy = createdPharmacies[1]; // MedCare Pharmacy Mirpur
    const sampleSale2 = await Sale.create({
      receiptId: 'MC-2026-784103',
      pharmacyId: mirpurPharmacy._id,
      customerId: customerUser._id,
      customerName: customerUser.name,
      customerPhone: customerUser.phone,
      items: [
        {
          medicineId: createdMedicines[3]._id, // Ace Plus
          medicineName: createdMedicines[3].name,
          genericName: createdMedicines[3].genericName,
          batchNumber: 'ACE-2026-01',
          quantity: 10,
          unitPrice: 2.50,
          totalPrice: 25.00,
        },
      ],
      subtotal: 25.00,
      discount: 0,
      totalPrice: 25.00,
      paymentMethod: 'Cash on Delivery',
      date: new Date(Date.now() - 1000 * 60 * 60 * 18), // 18 hours ago
    });

    const lazzMirpur = createdPharmacies[4]; // Lazz Pharma Mirpur
    const sampleSale3 = await Sale.create({
      receiptId: 'MC-2026-784104',
      pharmacyId: lazzMirpur._id,
      customerId: customerUser._id,
      customerName: customerUser.name,
      customerPhone: customerUser.phone,
      items: [
        {
          medicineId: createdMedicines[5]._id, // Sergel 20 mg
          medicineName: createdMedicines[5].name,
          genericName: createdMedicines[5].genericName,
          batchNumber: 'SER-2026-01',
          quantity: 14,
          unitPrice: 7.00,
          totalPrice: 98.00,
        },
      ],
      subtotal: 98.00,
      discount: 3.00,
      totalPrice: 95.00,
      paymentMethod: 'Nagad',
      date: new Date(Date.now() - 1000 * 60 * 60 * 4), // 4 hours ago
    });

    console.log('[Seed] Created sample digital sale receipts:', [sampleSale.receiptId, sampleSale2.receiptId, sampleSale3.receiptId]);

    // 7. Create Customer Medicine History
    await MedicineHistory.create([
      {
        customerId: customerUser._id,
        medicineId: createdMedicines[0]._id,
        medicineName: createdMedicines[0].name,
        genericName: createdMedicines[0].genericName,
        manufacturer: createdMedicines[0].manufacturer,
        batchNumber: 'NAPA-2026-01',
        verificationStatus: 'DATABASE MATCH',
        pharmacyId: mainPharmacy._id,
        pharmacyName: mainPharmacy.name,
        type: 'VERIFICATION',
        checkedAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
      },
      {
        customerId: customerUser._id,
        medicineId: createdMedicines[4]._id,
        medicineName: createdMedicines[4].name,
        genericName: createdMedicines[4].genericName,
        manufacturer: createdMedicines[4].manufacturer,
        batchNumber: 'SEC-2026-01',
        verificationStatus: 'PURCHASED',
        pharmacyId: mainPharmacy._id,
        pharmacyName: mainPharmacy.name,
        type: 'PURCHASE',
        notes: 'Purchased with digital receipt MC-2026-784102',
        checkedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
      },
      {
        customerId: customerUser._id,
        medicineId: createdMedicines[3]._id,
        medicineName: createdMedicines[3].name,
        genericName: createdMedicines[3].genericName,
        manufacturer: createdMedicines[3].manufacturer,
        batchNumber: 'ACE-2026-01',
        verificationStatus: 'PURCHASED',
        pharmacyId: mirpurPharmacy._id,
        pharmacyName: mirpurPharmacy.name,
        type: 'PURCHASE',
        notes: 'Purchased with digital receipt MC-2026-784103 (Home Delivery)',
        checkedAt: new Date(Date.now() - 1000 * 60 * 60 * 18),
      },
      {
        customerId: customerUser._id,
        medicineId: createdMedicines[5]._id,
        medicineName: createdMedicines[5].name,
        genericName: createdMedicines[5].genericName,
        manufacturer: createdMedicines[5].manufacturer,
        batchNumber: 'SER-2026-01',
        verificationStatus: 'PURCHASED',
        pharmacyId: lazzMirpur._id,
        pharmacyName: lazzMirpur.name,
        type: 'PURCHASE',
        notes: 'Purchased with digital receipt MC-2026-784104',
        checkedAt: new Date(Date.now() - 1000 * 60 * 60 * 4),
      },
      {
        customerId: customerUser._id,
        medicineId: createdMedicines[6]._id,
        medicineName: createdMedicines[6].name,
        genericName: createdMedicines[6].genericName,
        manufacturer: createdMedicines[6].manufacturer,
        batchNumber: 'MAX-2026-01',
        verificationStatus: 'DATABASE MATCH',
        type: 'VERIFICATION',
        checkedAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
      },
    ]);

    // 8. Create Sample Suspicious Medicine Reports
    await Report.create([
      {
        reportId: 'RPT-2026-1042',
        customerId: customerUser._id,
        customerName: customerUser.name,
        customerPhone: customerUser.phone,
        medicineName: 'Ace Plus',
        genericName: 'Paracetamol + Caffeine',
        manufacturer: 'Square Pharmaceuticals PLC',
        batchNumber: 'ACE-FLAG-88',
        pharmacyName: 'Local Corner Drugstore',
        pharmacyLocation: 'Mirpur 11, Dhaka',
        issueType: 'Suspected Counterfeit',
        description: 'The blister pack foil text was slightly smudged and tablets had an unusual powdery residue.',
        status: 'Under Investigation',
        adminNotes: 'Notified quality assurance division for sample cross-referencing.',
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72),
      },
      {
        reportId: 'RPT-2026-1088',
        customerId: customerUser2._id,
        customerName: customerUser2.name,
        customerPhone: customerUser2.phone,
        medicineName: 'Seclo 20 mg',
        genericName: 'Omeprazole',
        manufacturer: 'Square Pharmaceuticals PLC',
        batchNumber: 'SEC-OLD-2024',
        pharmacyName: 'Unregistered Vendor',
        pharmacyLocation: 'Mohakhali Bus Stand',
        issueType: 'Expired Medicine',
        description: 'Sold expired strip with scratched-out manufacturing date stamp.',
        status: 'Pending Review',
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
      },
    ]);

    // 9. Create Access Logs
    await AccessLog.create([
      {
        userEmail: 'admin@medcheckbd.com',
        userRole: 'admin',
        action: 'LOGIN',
        resourceType: 'Auth',
        details: 'Admin user logged in to secure portal',
        ipAddress: '127.0.0.1',
      },
      {
        userEmail: 'pharmacy@medcare.com',
        userRole: 'pharmacy',
        action: 'UPDATE_INVENTORY',
        resourceType: 'Inventory',
        details: 'Updated stock for Napa 500 mg (Batch: NAPA-2026-01)',
        ipAddress: '127.0.0.1',
      },
      {
        userEmail: 'customer@gmail.com',
        userRole: 'customer',
        action: 'VERIFY_MEDICINE',
        resourceType: 'Medicine',
        details: 'Verified medicine Napa 500 mg, Status: DATABASE MATCH',
        ipAddress: '127.0.0.1',
      },
    ]);

    console.log('[Seed] Database successfully seeded with 100% Bangladesh demo dataset!');
  } catch (err) {
    console.error('[Seed Error]', err);
  }
};

// Allow running directly via `node server/seed/seedData.js`
if (require.main === module) {
  const { connectDB, closeDB } = require('../config/db');
  connectDB().then(async () => {
    await seedDatabase();
    await closeDB();
    process.exit(0);
  });
}

module.exports = seedDatabase;
